routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(static function () {
    Route::resources([
        '/schools' => SchoolController::class,
        '/students' => StudentController::class
    ]);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/School.php
<?php

namespace App\Models;

use App\Models\Student;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class School extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
    ];

    /**
     * Get the student for the school.
     */
    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SchoolRequest;
use App\Http\Resources\SchoolCollectionResource;
use App\Http\Services\SchoolService;
use App\Models\School;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class SchoolController extends Controller
{
    public function __construct(public SchoolService $SchoolService){}

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index() :View
    {
        $schools = new SchoolCollectionResource(School::paginate(10));
        return view('schools/index',compact('schools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create() :view
    {
        $school = new School();
        return view('schools/create', compact('school'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\SchoolRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SchoolRequest $request) :RedirectResponse
    {
        $response = $this->SchoolService->fillFromRequest($request);
        if ($response) {
            return redirect()->route('schools.index')->with([
               'success' => "Created Successfully"
               ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\School  $school
     * @return \Illuminate\View\View
     */
    public function edit(School $school) :view
    {
        return view('schools/edit', compact('school'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\SchoolRequest  $request
     * @param  \App\Models\School  $school
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SchoolRequest $request, School $school) :RedirectResponse
    {
        $response = $this->SchoolService->fillFromRequest($request, $school);
        if ($response) {
            return redirect()->route('schools.index')->with([
               'success' => "Updated Successfully"
               ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\School  $school
     * @return @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(School $school) :RedirectResponse
    {
        $school->delete();
        return redirect()->route('schools.index')->with([
           'success' => "Deleted Successfully"
           ]);
    }
}

resources/views/schools/_form.blade.php
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" required value="{{ old('name', $school->name) }}"
            class="form-control mt-2" id="name" placeholder="School Name">
    </div>

resources/views/schools/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center">Add School</h1>
                <a href="{{ route('schools.index') }}"> Schools </a>
                <form class="form" action="{{ route('schools.store') }}" method="post">
                    @csrf
                    @include('schools/_form')
                    <div class="form-group mt-3">
                         <button type="submit" class="btn btn-primary mb-2">Save</button>
                    </div>
               </form>
            </div>
        </div>
    </div>
@endsection

resources/views/schools/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center">Edit School</h1>
                <a href="{{ route('schools.index') }}"> Schools </a>
                <form class="form" action="{{ route('schools.update',[$school->id]) }}" method="post">
                    @csrf
                    @method('PATCH')
                    @include('schools/_form')
                    <div class="form-group mt-3">
                         <button type="submit" class="btn btn-primary mb-2">Edit</button>
                    </div>
               </form>
            </div>
        </div>
    </div>
@endsection

resources/views/schools/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center">Schools</h1>
                <a href="{{ route('schools.create') }}"> Add School </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($schools as $school)
                            <tr>
                                <th scope="row">{{ $school->id }}</th>
                                <td>{{ $school->name }}</td>
                                <td><a href="{{ route('schools.edit',[$school->id]) }}">
                                    <i class="fa fa-edit"></i>
                                </a></td>
                                <td>
                                    <form class="" action="{{ route('schools.destroy',[$school->id]) }}" method="post">
                                        @csrf
                                        @method('Delete')
                                        <button type="submit">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $schools->links() }}
            </div>
        </div>
    </div>
@endsection